// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDX22hrPGxvXzRkqKwzbCdjyrNL6-axTNw',
    appId: '1:396452244841:web:d3562baa92ce67d7aaa1f8',
    messagingSenderId: '396452244841',
    projectId: 'promote-her-f52c2',
    authDomain: 'promote-her-f52c2.firebaseapp.com',
    storageBucket: 'promote-her-f52c2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2qtbS7A_XKBD9L_mbTcs4Gx89bXovkSY',
    appId: '1:396452244841:android:ae1049558a87289daaa1f8',
    messagingSenderId: '396452244841',
    projectId: 'promote-her-f52c2',
    storageBucket: 'promote-her-f52c2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxnzphev_8PMwjroLI67US2ac7PqJEXX4',
    appId: '1:396452244841:ios:fb53e678b864d90eaaa1f8',
    messagingSenderId: '396452244841',
    projectId: 'promote-her-f52c2',
    storageBucket: 'promote-her-f52c2.appspot.com',
    iosBundleId: 'com.example.flutterearn',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxnzphev_8PMwjroLI67US2ac7PqJEXX4',
    appId: '1:396452244841:ios:fb53e678b864d90eaaa1f8',
    messagingSenderId: '396452244841',
    projectId: 'promote-her-f52c2',
    storageBucket: 'promote-her-f52c2.appspot.com',
    iosBundleId: 'com.example.flutterearn',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDX22hrPGxvXzRkqKwzbCdjyrNL6-axTNw',
    appId: '1:396452244841:web:adb9ba61afd45a5aaaa1f8',
    messagingSenderId: '396452244841',
    projectId: 'promote-her-f52c2',
    authDomain: 'promote-her-f52c2.firebaseapp.com',
    storageBucket: 'promote-her-f52c2.appspot.com',
  );

}